#!/usr/bin/env zsh
# record_env.zsh [output-path]
# Writes a machine's environment record (default: docs/environment/<machine>.md).
# Generated, never hand-edited: transcribing values by hand is how records rot.
# Runs tools/bench_context.zsh first, so it refuses the same unreproducible
# states (active conda, exported CC/CXX).
set -euo pipefail
root="$(git rev-parse --show-toplevel)"
cd "$root"

ctx=$(./tools/bench_context.zsh)          # guards + machine id + versions
machine=$(print -r -- "$ctx" | jq -r .machine)
out="${1:-docs/environment/${machine}.md}"
mkdir -p "${out:h}"

# --- hardware ------------------------------------------------------------
model=$(system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/Model Name/{print $2; exit}')
chip=$(sysctl -n machdep.cpu.brand_string)
mem_gb=$(( $(sysctl -n hw.memsize) / 1024 / 1024 / 1024 ))
p_cores=$(sysctl -n hw.perflevel0.logicalcpu 2>/dev/null || print '?')
e_cores=$(sysctl -n hw.perflevel1.logicalcpu 2>/dev/null || print '?')
gpu_cores=$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/Total Number of Cores/{print $2; exit}')

# --- toolchain -----------------------------------------------------------
apple_cxx=/usr/bin/clang++
brew_cxx=/opt/homebrew/opt/llvm/bin/clang++
metal_id=$(xcodebuild -showComponent MetalToolchain 2>/dev/null | awk -F': ' '/^Toolchain Identifier/{print $2}')

first_line() { "$@" 2>&1 | head -1 }

# Every __cpp_lib_ macro. Dumping all of them avoids grepping for "mdspan"
# and silently missing "submdspan".
cpp_lib() {
  print -r -- '#include <version>' \
    | "$1" -std=c++2c -x c++ -E -dM - 2>/dev/null | grep '^#define __cpp_lib_' | sort
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
cpp_lib "$apple_cxx" > "$tmp/apple.txt"
if [[ -x "$brew_cxx" ]]; then cpp_lib "$brew_cxx" > "$tmp/brew.txt"; else : > "$tmp/brew.txt"; fi

{
  print -r -- "# Environment: ${machine}"
  print -r -- ""
  print -r -- "Generated by \`tools/record_env.zsh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit by hand."
  print -r -- ""
  print -r -- "## Context (benchmark schema v1)"
  print -r -- ""
  print -r -- '```json'
  print -r -- "$ctx"
  print -r -- '```'
  print -r -- ""
  print -r -- "## Hardware"
  print -r -- ""
  print -r -- "| Item | Value |"
  print -r -- "|---|---|"
  print -r -- "| Model | ${model:-unknown} |"
  print -r -- "| Chip | ${chip} |"
  print -r -- "| Memory | ${mem_gb} GB unified |"
  print -r -- "| CPU cores | P ${p_cores} / E ${e_cores} |"
  print -r -- "| GPU cores | ${gpu_cores:-unknown} |"
  print -r -- "| Cooling | fanless |"
  print -r -- ""
  print -r -- "## Toolchain"
  print -r -- ""
  print -r -- "| Item | Value |"
  print -r -- "|---|---|"
  print -r -- "| Apple Clang | $(first_line "$apple_cxx" --version) |"
  if [[ -x "$brew_cxx" ]]; then
    print -r -- "| Homebrew LLVM | $(first_line "$brew_cxx" --version) |"
  else
    print -r -- "| Homebrew LLVM | not installed |"
  fi
  print -r -- "| Metal compiler | $(first_line xcrun -sdk macosx metal --version) |"
  print -r -- "| Metal Toolchain id | ${metal_id:-unknown} |"
  print -r -- "| CMake | $(first_line cmake --version) |"
  print -r -- "| Ninja | $(first_line ninja --version) |"
  print -r -- ""
  print -r -- "## ARM features (\`sysctl hw.optional.arm\`)"
  print -r -- ""
  print -r -- '```'
  sysctl hw.optional.arm 2>/dev/null | sort || print -r -- "(unavailable)"
  print -r -- '```'
  print -r -- ""
  print -r -- "## C++ library feature macros (\`-std=c++2c\`)"
  print -r -- ""
  print -r -- "Apple Clang: $(wc -l < "$tmp/apple.txt" | tr -d ' ') macros. Homebrew LLVM: $(wc -l < "$tmp/brew.txt" | tr -d ' ') macros."
  print -r -- ""
  print -r -- "### Difference (\`<\` Apple Clang, \`>\` Homebrew LLVM)"
  print -r -- ""
  print -r -- '```diff'
  diff "$tmp/apple.txt" "$tmp/brew.txt" || true
  print -r -- '```'
  print -r -- ""
  print -r -- "### Apple Clang (default compiler)"
  print -r -- ""
  print -r -- '```'
  cat "$tmp/apple.txt"
  print -r -- '```'
} > "$out"

print -r -- "wrote ${out} ($(wc -l < "$out" | tr -d ' ') lines)"
